name: CD

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build, and test
      run: |
        yarn
        yarn lerna bootstrap
        yarn build:ci
        yarn test
    - name: deploy frontend to gh pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: packages/client/build # The folder the action should deploy.
    - name: deploy backend to now
      run: |
        yarn lerna run deploy --scope api -- -- --token ${{ secrets.ZEIT_TOKEN }}
      env:
        CI: true
